name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Dotnet Publish
      run: dotnet publish --runtime win-x86 --configuration Release
    - name: Create ZIP
      shell: pwsh
      run: |
        cd .\bin\Release\netcoreapp3.1\win-x86\
        mv publish ChannelsDemo
        Compress-Archive -Path .\ChannelsDemo -DestinationPath ChannelsDemo.zip
    - name: Upload to Existing Release
      uses: Shopify/upload-to-release@1.0.0
      with:
        name: ChannelsDemo.zip
        path: bin\Release\netcoreapp3.0\win-x86\ChannelsDemo.zip
        repo-token: ${{ secrets.GITHUB_TOKEN }}
